NORWEGIAN = {
    "GEN": "1. Mosebok",      "EXO": "2. Mosebok",      "LEV": "3. Mosebok",
    "NUM": "4. Mosebok",      "DEU": "5. Mosebok",       "JOS": "Josva",
    "JDG": "Dommerne",        "RUT": "Rut",              "1SA": "1. Samuelsbok",
    "2SA": "2. Samuelsbok",   "1KI": "1. Kongebok",      "2KI": "2. Kongebok",
    "1CH": "1. Krønikebok",   "2CH": "2. Krønikebok",    "EZR": "Esra",
    "NEH": "Nehemja",         "EST": "Ester",             "JOB": "Job",
    "PSA": "Salme",           "PRO": "Ordspråkene",       "ECC": "Forkynneren",
    "SNG": "Høysangen",       "ISA": "Jesaja",            "JER": "Jeremia",
    "LAM": "Klagesangene",    "EZK": "Esekiel",           "DAN": "Daniel",
    "HOS": "Hosea",           "JOL": "Joel",              "AMO": "Amos",
    "OBA": "Obadja",          "JON": "Jona",              "MIC": "Mika",
    "NAM": "Nahum",           "HAB": "Habakkuk",          "ZEP": "Sefanja",
    "HAG": "Haggai",          "ZEC": "Sakarja",           "MAL": "Malaki",
    "MAT": "Matteus",         "MRK": "Markus",            "LUK": "Lukas",
    "JHN": "Johannes",        "ACT": "Apostlenes gjerninger",
    "ROM": "Romerne",         "1CO": "1. Korinterbrev",   "2CO": "2. Korinterbrev",
    "GAL": "Galaterne",       "EPH": "Efeserne",          "PHP": "Filipperne",
    "COL": "Kolosserne",      "1TH": "1. Tessalonikerbrev", "2TH": "2. Tessalonikerbrev",
    "1TI": "1. Timoteus",     "2TI": "2. Timoteus",       "TIT": "Titus",
    "PHM": "Filemon",         "HEB": "Hebreerne",         "JAS": "Jakob",
    "1PE": "1. Peter",        "2PE": "2. Peter",          "1JN": "1. Johannesbrev",
    "2JN": "2. Johannesbrev", "3JN": "3. Johannesbrev",   "JUD": "Judas",
    "REV": "Åpenbaringen",
}

ENGLISH = {
    "GEN": "Genesis",         "EXO": "Exodus",           "LEV": "Leviticus",
    "NUM": "Numbers",         "DEU": "Deuteronomy",      "JOS": "Joshua",
    "JDG": "Judges",          "RUT": "Ruth",             "1SA": "1 Samuel",
    "2SA": "2 Samuel",        "1KI": "1 Kings",          "2KI": "2 Kings",
    "1CH": "1 Chronicles",    "2CH": "2 Chronicles",     "EZR": "Ezra",
    "NEH": "Nehemiah",        "EST": "Esther",            "JOB": "Job",
    "PSA": "Psalms",          "PRO": "Proverbs",          "ECC": "Ecclesiastes",
    "SNG": "Song of Solomon", "ISA": "Isaiah",            "JER": "Jeremiah",
    "LAM": "Lamentations",    "EZK": "Ezekiel",           "DAN": "Daniel",
    "HOS": "Hosea",           "JOL": "Joel",              "AMO": "Amos",
    "OBA": "Obadiah",         "JON": "Jonah",             "MIC": "Micah",
    "NAM": "Nahum",           "HAB": "Habakkuk",          "ZEP": "Zephaniah",
    "HAG": "Haggai",          "ZEC": "Zechariah",         "MAL": "Malachi",
    "MAT": "Matthew",         "MRK": "Mark",              "LUK": "Luke",
    "JHN": "John",            "ACT": "Acts",
    "ROM": "Romans",          "1CO": "1 Corinthians",     "2CO": "2 Corinthians",
    "GAL": "Galatians",       "EPH": "Ephesians",         "PHP": "Philippians",
    "COL": "Colossians",      "1TH": "1 Thessalonians",   "2TH": "2 Thessalonians",
    "1TI": "1 Timothy",       "2TI": "2 Timothy",         "TIT": "Titus",
    "PHM": "Philemon",        "HEB": "Hebrews",           "JAS": "James",
    "1PE": "1 Peter",         "2PE": "2 Peter",           "1JN": "1 John",
    "2JN": "2 John",          "3JN": "3 John",            "JUD": "Jude",
    "REV": "Revelation",
}
